repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            exclude: '.*\.(txt|csv)'
          - id: end-of-file-fixer
            exclude: '.*\.(txt|csv)'
          - id: check-yaml
            exclude: '.*\.(txt|csv)'

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            name: pyupgrade (.py files)

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ['--profile', 'black']
            name: isort (.py files)

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            name: black (.py files)

    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            name: flake8 (.py files)

    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout
            name: nbstripout (.ipynb files)

    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.6.1
      hooks:
          - id: nbqa-pyupgrade
            args: ['--py39-plus']
            name: pyupgrade (.ipynb files)
          - id: nbqa-isort
            args: ['--float-to-top']
            name: isort (.ipynb files)
          - id: nbqa-black
            name: black (.ipynb files)
# don't run flake8 on notebooks, it's too aggressive
#      - id: nbqa-flake8
#        name: flake8 (.ipynb files)
