repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: '.*\.(txt|csv)'
      - id: end-of-file-fixer
        exclude: '.*\.(txt|csv)'
      - id: check-yaml
        exclude: '.*\.(txt|csv)'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: pyupgrade (.py files)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.2'
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]



  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: nbstripout (.ipynb files)


  - repo: local
    hooks:
      - id: pyclean
        name: pyclean
        entry: poetry run pyclean .
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
